name: sisterhood_global
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.13.0
  firebase_analytics: ^9.1.1
  firebase_auth: ^3.3.8
  cloud_firestore: ^3.1.9
  get_storage: ^2.0.2
  firebase_messaging: ^11.2.7
  firebase_storage: ^10.2.8
  google_sign_in: ^5.2.4
  get: ^4.6.1
  fluttertoast: ^8.0.9
  http: ^0.13.4
  youtube_player_flutter: ^8.0.0
  file_picker: ^4.4.0
  dio: ^4.0.4
  share_extend: ^2.0.0
  permission_handler: ^9.2.0
  #badges: ^1.2.0
  image_picker: ^0.8.4+9
  photo_view: ^0.13.0
  image_cropper: ^1.5.0
  flutter_svg: ^1.0.3
  country_code_picker: ^2.0.2
  #timeago: ^3.0.2
  flutter_auth_buttons: ^0.10.0
  intl: ^0.17.0
  url_launcher:
  google_fonts: ^2.3.1
  cached_network_image: ^3.2.0
  progress_dialog: ^1.2.4
  sticky_grouped_list: ^2.1.0
  flutter_local_notifications: ^9.3.2
  responsive_framework: ^0.1.7
  new_version: ^0.3.0
  webview_flutter: ^3.0.1
  paginate_firestore: ^1.0.3
  flutter_linkify: ^5.0.2
  font_awesome_flutter: ^9.2.0
  #flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_bdaya: ^2.0.0
  flutter_dropdown: ^1.0.0+hotfix.1
  #animated_bottom_navigation_bar: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
     - images/
