name: sisterhood_global
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.1.1
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.0.1
  google_sign_in: ^5.1.1
  get: ^4.3.8
  fluttertoast: ^8.0.3
  http: ^0.13.1
  youtube_player_flutter: ^8.0.0
  file_picker: ^3.0.0
  #dio: ^4.0.0
  #share_extend: ^1.1.9
  permission_handler: ^6.1.1
  #badges: ^1.2.0
  image_picker: ^0.7.3
  photo_view: ^0.11.1
  image_cropper: ^1.4.1
  flutter_svg: ^0.22.0
  country_code_picker: ^2.0.2
  shimmer: ^2.0.0
  pull_to_refresh: ^2.0.0
  #timeago: ^3.0.2
  flutter_auth_buttons: ^0.10.0
  intl: ^0.17.0
  url_launcher:
  google_fonts: ^2.0.0
  cached_network_image: ^3.0.0
  progress_dialog: ^1.2.4
  sticky_grouped_list: ^1.3.0
  flutter_local_notifications: ^5.0.0
  #firebase_image: ^0.3.0
  webview_flutter: ^2.0.2
  #location: ^4.1.1
  #google_maps_flutter: ^2.0.1
  #flutter_quill: ^1.1.4
  #swipe_to: ^0.0.1+8
  #flutter_inappwebview: ^5.3.1
  paginate_firestore: ^0.3.1
  flutter_linkify: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - images/
