name: sisterhood_global
description: A project for sisterhood global community.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+10
#IOS 1.0.10+11
#android 1.0.9+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.10
  get_storage: ^2.0.3
  firebase_messaging: ^11.2.10
  firebase_storage: ^10.2.9
  google_sign_in: ^5.2.4
  sign_in_with_apple: ^3.3.0
  get: ^4.6.1
  fluttertoast: ^8.0.9
  http: ^0.13.4
  youtube_player_flutter: ^8.0.0
  #youtube_player_iframe: ^2.2.2
  file_picker: ^4.5.1
  dio: ^4.0.4
  share_extend: ^2.0.0
  permission_handler: ^9.2.0
  crypto: ^3.0.1
  #badges: ^1.2.0
  image_picker: ^0.8.4+11
  photo_view: ^0.13.0
  image_cropper: ^1.5.0
  flutter_svg: ^1.0.3
  country_code_picker: ^2.0.2
  #timeago: ^3.0.2
  flutter_auth_buttons: ^0.10.0
  intl: ^0.17.0
  url_launcher:
  google_fonts: ^2.3.1
  cached_network_image: ^3.2.0
  progress_dialog: ^1.2.4
  sticky_grouped_list: ^2.1.0
  flutter_local_notifications: ^9.4.0
  responsive_framework: ^0.1.7
  new_version: ^0.3.0
  #webview_flutter: ^3.0.1
  paginate_firestore: ^1.0.3
  flutter_linkify: ^5.0.2
  font_awesome_flutter: ^9.2.0
  flutter_datetime_picker_bdaya: ^2.0.0
  flutter_dropdown: ^1.0.0+hotfix.1
  shared_preferences: ^2.0.13
  #flutter_firebase_chat_core: ^1.5.2
  #device_preview: ^1.0.0
  #linkfy_text: ^1.1.5
  #flutter_secure_storage: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  modal_bottom_sheet: ^2.0.1
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "images/logo3.png"

dependency_overrides:
  webview_flutter: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
     - images/
